id: I88CCE641
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:12:18+00:00'
last_modified: '2022-06-09T05:00:26.970045+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9827
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ཟླ་བའི་སྒྲོན་མེ་དང་ཉི་མའི་འོད་ཟེར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FB6A:
      image_group_id: I1KG9837
      title: ''
      total_pages: 780
      order: 1
      base_file: FB6A.txt
    7A20:
      image_group_id: I1KG9838
      title: ''
      total_pages: 618
      order: 2
      base_file: 7A20.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
