id: I88CCE641
legacy_id: P008173
ocr_import_info:
  bdrc_scan_id: W1KG9827
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T10:07:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:39:59.847596+00:00'
last_modified: 2022-09-01 02:40:39.579006
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9827
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9827
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཡོན་ཏན་རིན་པོ་ཆེའི་མཛོད་ཀྱི་འགྲེལ་པ་ཟླ་བའི་སྒྲོན་མེ་དང་ཉི་མའི་འོད་ཟེར།
  author: དགེ་མང་མཁན་ཆེན་ཡོན་ཏན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7717040000527802
  ocr_word_median_confidence_index: 0.8299999833106995
quality: null
bases:
  I1KG9838:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9838
      total_pages: 618
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG9838.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7520924175890479
    legacy_id: v002
  I1KG9837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9837
      total_pages: 780
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9837.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7873696647402261
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
